version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
  - package-ecosystem: "pip"
    directory: "/firmware/bridge"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
