// Package protocol implements the Tether LoRa wire format.
//
// The wire format is defined in proto/tether.proto. The generated
// protobuf structs live in the protocolpb subpackage; this file holds
// the hand-written helpers (CRC, encode, decode, validation) that
// plan.md §1.4 puts alongside the schema.
//
// Wire layout:
//
//	The Envelope is encoded as a single protobuf message. The
//	`header_crc` field is filled in by Encode, holding a CRC-16/CCITT-
//	FALSE of the rest of the encoded message (everything except the
//	CRC field itself, which is zeroed before computing). The high
//	sixteen bits of the uint32 are always zero — CRC-16 fits in 16
//	bits and we pad for forward-compatibility.
package protocol

import (
	"errors"
	"fmt"

	"google.golang.org/protobuf/proto"

	"github.com/jbutlerdev/tether/go/pkg/protocol/protocolpb"
)

// MaxPayloadSize is the largest single-chunk payload allowed on the
// LoRa link. 227 bytes leaves room for header, CRC, and MAC inside a
// 256-byte frame. Plan §1.4.
const MaxPayloadSize = 227

// MaxConvNameLen matches the M5 EPD's 24-char name field.
const MaxConvNameLen = 24

// Sentinel errors. Tests assert on these with errors.Is.
var (
	ErrPayloadTooLarge = errors.New("protocol: payload exceeds max chunk size")
	ErrBadCRC          = errors.New("protocol: envelope CRC mismatch")
	ErrTruncated       = errors.New("protocol: wire buffer too short")
	ErrNameTooLong     = errors.New("protocol: conversation name exceeds 24 chars")
)

// Crc16CCITT computes the CRC-16/CCITT-FALSE of buf.
//
// Parameters (per plan.md §1.4 / §2.1):
//
//	polynomial     0x1021
//	init           0xFFFF
//	reflect input  false
//	reflect output false
//	xorout         0x0000
//
// Reference test vector: "123456789" → 0x29B1.
func Crc16CCITT(buf []byte) uint16 {
	// Table-driven implementation. The table is 256 entries × 2 bytes,
	// generated by the standard CRC-16/CCITT-FALSE polynomial.
	var table [256]uint16
	for i := 0; i < 256; i++ {
		crc := uint16(i) << 8
		for j := 0; j < 8; j++ {
			if crc&0x8000 != 0 {
				crc = (crc << 1) ^ 0x1021
			} else {
				crc <<= 1
			}
		}
		table[i] = crc
	}

	crc := uint16(0xFFFF)
	for _, b := range buf {
		crc = (crc << 8) ^ table[byte(crc>>8)^b]
	}
	return crc
}

// Encode marshals env, computes the CRC over the marshaled message
// (with the CRC field zeroed), and re-marshals with the CRC populated.
func Encode(env *protocolpb.Envelope) ([]byte, error) {
	if env == nil {
		return nil, errors.New("protocol: nil envelope")
	}
	if len(env.Payload) > MaxPayloadSize {
		return nil, fmt.Errorf("payload length %d > %d: %w", len(env.Payload), MaxPayloadSize, ErrPayloadTooLarge)
	}

	// First pass: marshal with CRC=0. We use proto.Clone rather than a
	// struct copy because the generated Envelope embeds a sync.Mutex for
	// concurrent access, and copying a mutex is a vet-flagged bug. The
	// type assertion is safe: proto.Clone always returns a value of the
	// same concrete type as the input.
	scratch := proto.Clone(env).(*protocolpb.Envelope)
	scratch.HeaderCrc = 0
	first, err := protoMarshal(scratch)
	if err != nil {
		return nil, fmt.Errorf("encode marshal: %w", err)
	}

	crc := Crc16CCITT(first)
	scratch.HeaderCrc = uint32(crc) // high 16 bits stay 0 — CRC-16 fits in 16
	second, err := protoMarshal(scratch)
	if err != nil {
		return nil, fmt.Errorf("encode re-marshal: %w", err)
	}
	return second, nil
}

// Decode parses a wire buffer into an Envelope, verifying the CRC.
func Decode(buf []byte) (*protocolpb.Envelope, error) {
	if len(buf) < 8 {
		// Even the most minimal Envelope (no payload, no conv id) is
		// much larger than 8 bytes after protobuf encoding.
		return nil, ErrTruncated
	}

	env := &protocolpb.Envelope{}
	if err := protoUnmarshal(buf, env); err != nil {
		return nil, fmt.Errorf("decode unmarshal: %w", err)
	}

	// Verify the CRC by re-marshaling with the field zeroed and
	// recomputing. The stored CRC must match.
	stored := env.HeaderCrc
	env.HeaderCrc = 0
	re, err := protoMarshal(env)
	if err != nil {
		return nil, fmt.Errorf("decode re-marshal: %w", err)
	}
	if Crc16CCITT(re) != uint16(stored) {
		return nil, ErrBadCRC
	}
	// Restore so the caller sees the value we received.
	env.HeaderCrc = stored
	return env, nil
}

// MarshalAck serializes an Ack to its on-the-wire form.
//
// Phase 0 keeps the wire format identical to the protobuf encoding of
// the Ack message (the CRC field is a 0 placeholder until Phase 1
// wires up the cumulative bitmap state machine).
func MarshalAck(ack *protocolpb.Ack) ([]byte, error) {
	if ack == nil {
		return nil, errors.New("protocol: nil ack")
	}
	return protoMarshal(ack)
}

// DecodeAck parses a wire buffer into an Ack.
func DecodeAck(buf []byte) (*protocolpb.Ack, error) {
	if len(buf) == 0 {
		return nil, ErrTruncated
	}
	ack := &protocolpb.Ack{}
	if err := protoUnmarshal(buf, ack); err != nil {
		return nil, fmt.Errorf("decode ack: %w", err)
	}
	return ack, nil
}

// ValidateConvInfo checks that a UI_UPDATE payload is well-formed.
// It rejects names longer than the M5 EPD can display.
func ValidateConvInfo(ci *protocolpb.ConvInfo) error {
	if ci == nil {
		return errors.New("protocol: nil conv info")
	}
	if len(ci.Name) > MaxConvNameLen {
		return fmt.Errorf("name length %d > %d: %w", len(ci.Name), MaxConvNameLen, ErrNameTooLong)
	}
	return nil
}

// protoMarshal and protoUnmarshal are swappable in tests so the
// "second marshal fails" / "unmarshal returns error" branches can be
// exercised. In production they are direct calls to the protobuf
// library; the test in header_test.go swaps them with a stub that
// always returns an error.
var (
	protoMarshal   = proto.Marshal
	protoUnmarshal = proto.Unmarshal
)

// ProtoMarshalFunc is the type of a swappable proto.Marshal replacement.
type ProtoMarshalFunc func(proto.Message) ([]byte, error)

// ProtoUnmarshalFunc is the type of a swappable proto.Unmarshal replacement.
type ProtoUnmarshalFunc func([]byte, proto.Message) error

// SwapProtoMarshal replaces protoMarshal for the duration of a test and
// returns the previous function so callers can restore it (typically
// via t.Cleanup). Not safe to call from multiple goroutines; tests only.
func SwapProtoMarshal(fn ProtoMarshalFunc) ProtoMarshalFunc {
	prev := protoMarshal
	protoMarshal = fn
	return prev
}

// SwapProtoUnmarshal is the unmarshal counterpart of SwapProtoMarshal.
func SwapProtoUnmarshal(fn ProtoUnmarshalFunc) ProtoUnmarshalFunc {
	prev := protoUnmarshal
	protoUnmarshal = fn
	return prev
}
