// Package protocol implements the Tether LoRa wire format.
//
// The wire format is the fixed binary header defined in
// research.md §8.1 (reconciled). The in-memory representation is
// the generated protobuf structs in the protocolpb subpackage;
// this file holds the hand-written codec (CRC, fixed-header
// encode/decode, validation) that puts those structs on the wire.
//
// Wire layout — fixed 34-byte header followed by ≤ MaxPayloadSize
// bytes of payload (research.md §8.1):
//
//	Offset  Size  Field
//	0       2     target_id        // LE uint16; 0xFFFF = broadcast
//	2       2     sender_id        // LE uint16
//	4       16    conversation_id  // UUID
//	20      4     message_id       // LE uint32; monotonic per conv
//	24      2     seq_num          // LE uint16; chunk index
//	26      2     total_seqs       // LE uint16; total chunks
//	28      1     msg_type         // START/DATA/END/ACK/TTS_DATA/...
//	29      1     flags            // bit0=RETRANSMIT, bit1=LAST_TTS
//	30      1     audio_kind       // 0=mic, 1=tts, 2=beep
//	31      1     reserved         // 0
//	32      2     header_crc       // CRC-16/CCITT-FALSE over bytes 0..31
//	34      …     payload          // ≤ MaxPayloadSize bytes
//
// The header is fixed-width so the M5 firmware (C++ mirror in
// firmware/m5/components/protocol) and the bridge can parse it
// without a protobuf runtime. conversation_id (16 bytes) lets a
// single radio participate in many Matrix rooms and forge sessions
// without address-space collisions; message_id (4 bytes) makes
// (conversation_id, message_id) globally monotonic and replay-safe
// (research.md §8.5). The CRC-16/CCITT-FALSE covers every header
// byte except itself, so a single-bit air corruption is caught
// before the payload is touched.
//
// MaxPayloadSize: the SX1262 FIFO is 255 bytes; the 34-byte header
// leaves 221 bytes for payload (255 − 34). The fragmentation logic
// (fragment.go) splits on this constant.
package protocol

import (
	"encoding/binary"
	"errors"
	"fmt"

	"github.com/jbutlerdev/tether/go/pkg/protocol/protocolpb"
)

// MaxPayloadSize is the largest single-chunk payload allowed on the
// LoRa link. 255-byte SX1262 FIFO minus the 34-byte fixed header
// (research.md §8.1).
const MaxPayloadSize = 221

// MaxConvNameLen matches the M5 EPD's 24-char name field.
const MaxConvNameLen = 24

// Wire header size (research.md §8.1).
const headerSize = 34

// Sentinel errors. Tests assert on these with errors.Is.
var (
	ErrPayloadTooLarge = errors.New("protocol: payload exceeds max chunk size")
	ErrBadCRC          = errors.New("protocol: envelope CRC mismatch")
	ErrTruncated       = errors.New("protocol: wire buffer too short")
	ErrNameTooLong     = errors.New("protocol: conversation name exceeds 24 chars")
)

// Crc16CCITT computes the CRC-16/CCITT-FALSE of buf.
//
// Parameters (per research.md §8.1):
//
//	polynomial     0x1021
//	init           0xFFFF
//	reflect input  false
//	reflect output false
//	xorout         0x0000
//
// Reference test vector: "123456789" → 0x29B1.
func Crc16CCITT(buf []byte) uint16 {
	// Table-driven implementation. The table is 256 entries × 2 bytes,
	// generated by the standard CRC-16/CCITT-FALSE polynomial.
	var table [256]uint16
	for i := 0; i < 256; i++ {
		crc := uint16(i) << 8
		for j := 0; j < 8; j++ {
			if crc&0x8000 != 0 {
				crc = (crc << 1) ^ 0x1021
			} else {
				crc <<= 1
			}
		}
		table[i] = crc
	}

	crc := uint16(0xFFFF)
	for _, b := range buf {
		crc = (crc << 8) ^ table[byte(crc>>8)^b]
	}
	return crc
}

// Encode serialises env into the fixed 34-byte header + payload wire
// format (research.md §8.1). The header_crc field is computed over
// header bytes 0..31 and written at offset 32.
func Encode(env *protocolpb.Envelope) ([]byte, error) {
	if env == nil {
		return nil, errors.New("protocol: nil envelope")
	}
	if len(env.Payload) > MaxPayloadSize {
		return nil, fmt.Errorf("payload length %d > %d: %w", len(env.Payload), MaxPayloadSize, ErrPayloadTooLarge)
	}
	if len(env.ConversationId) != 0 && len(env.ConversationId) != 16 {
		return nil, fmt.Errorf("conversation_id length %d, want 16: %w", len(env.ConversationId), ErrTruncated)
	}

	out := make([]byte, headerSize+len(env.Payload))
	// Bytes 0..1: target_id (LE uint16 from NodeId.value).
	binary.LittleEndian.PutUint16(out[0:2], uint16(nodeIDValue(env.TargetId)))
	// Bytes 2..3: sender_id.
	binary.LittleEndian.PutUint16(out[2:4], uint16(nodeIDValue(env.SenderId)))
	// Bytes 4..19: conversation_id (16 bytes; zero-padded if absent).
	if len(env.ConversationId) == 16 {
		copy(out[4:20], env.ConversationId)
	}
	// Bytes 20..23: message_id (LE uint32).
	binary.LittleEndian.PutUint32(out[20:24], env.MessageId)
	// Bytes 24..25: seq_num (LE uint16).
	binary.LittleEndian.PutUint16(out[24:26], uint16(env.SeqNum))
	// Bytes 26..27: total_seqs (LE uint16).
	binary.LittleEndian.PutUint16(out[26:28], uint16(env.TotalSeqs))
	// Byte 28: msg_type.
	out[28] = byte(env.MsgType)
	// Byte 29: flags (low 8 bits; bit0=RETRANSMIT, bit1=LAST_TTS).
	out[29] = byte(env.Flags)
	// Byte 30: audio_kind.
	out[30] = byte(env.AudioKind)
	// Byte 31: reserved (0).
	out[31] = 0
	// Bytes 32..33: header_crc over bytes 0..31.
	crc := Crc16CCITT(out[0:32])
	binary.LittleEndian.PutUint16(out[32:34], crc)
	// Payload.
	copy(out[34:], env.Payload)
	return out, nil
}

// Decode parses a fixed-header wire buffer into an Envelope, verifying
// the header CRC. The returned Envelope has ProtocolVersion=1 (the
// fixed format carries no version byte; the format itself is the
// version) and HeaderCrc populated with the on-wire CRC.
func Decode(buf []byte) (*protocolpb.Envelope, error) {
	if len(buf) < headerSize {
		return nil, fmt.Errorf("wire buffer %d < header %d: %w", len(buf), headerSize, ErrTruncated)
	}
	stored := binary.LittleEndian.Uint16(buf[32:34])
	if Crc16CCITT(buf[0:32]) != stored {
		return nil, ErrBadCRC
	}
	convID := make([]byte, 16)
	copy(convID, buf[4:20])
	env := &protocolpb.Envelope{
		ProtocolVersion: 1,
		TargetId:        &protocolpb.NodeId{Value: uint32(binary.LittleEndian.Uint16(buf[0:2]))},
		SenderId:        &protocolpb.NodeId{Value: uint32(binary.LittleEndian.Uint16(buf[2:4]))},
		ConversationId:  convID,
		MessageId:       binary.LittleEndian.Uint32(buf[20:24]),
		SeqNum:          uint32(binary.LittleEndian.Uint16(buf[24:26])),
		TotalSeqs:       uint32(binary.LittleEndian.Uint16(buf[26:28])),
		MsgType:         protocolpb.MsgType(buf[28]),
		Flags:           uint32(buf[29]),
		AudioKind:       protocolpb.AudioKind(buf[30]),
		HeaderCrc:       uint32(stored),
		Payload:         append([]byte(nil), buf[headerSize:]...),
	}
	return env, nil
}

// nodeIDValue safely dereferences a NodeId pointer, returning 0 for nil.
func nodeIDValue(n *protocolpb.NodeId) uint32 {
	if n == nil {
		return 0
	}
	return n.Value
}

// ValidateConvInfo checks that a UI_UPDATE payload is well-formed.
// It rejects names longer than the M5 EPD can display.
func ValidateConvInfo(ci *protocolpb.ConvInfo) error {
	if ci == nil {
		return errors.New("protocol: nil conv info")
	}
	if len(ci.Name) > MaxConvNameLen {
		return fmt.Errorf("name length %d > %d: %w", len(ci.Name), MaxConvNameLen, ErrNameTooLong)
	}
	return nil
}
