// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: tether.proto

package protocolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	MsgType_MSG_TYPE_START       MsgType = 1
	MsgType_MSG_TYPE_DATA        MsgType = 2
	MsgType_MSG_TYPE_END         MsgType = 3
	MsgType_MSG_TYPE_ACK         MsgType = 4
	MsgType_MSG_TYPE_TTS_DATA    MsgType = 5
	MsgType_MSG_TYPE_TTS_END     MsgType = 6
	MsgType_MSG_TYPE_UI_UPDATE   MsgType = 7
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNSPECIFIED",
		1: "MSG_TYPE_START",
		2: "MSG_TYPE_DATA",
		3: "MSG_TYPE_END",
		4: "MSG_TYPE_ACK",
		5: "MSG_TYPE_TTS_DATA",
		6: "MSG_TYPE_TTS_END",
		7: "MSG_TYPE_UI_UPDATE",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED": 0,
		"MSG_TYPE_START":       1,
		"MSG_TYPE_DATA":        2,
		"MSG_TYPE_END":         3,
		"MSG_TYPE_ACK":         4,
		"MSG_TYPE_TTS_DATA":    5,
		"MSG_TYPE_TTS_END":     6,
		"MSG_TYPE_UI_UPDATE":   7,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_tether_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_tether_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{0}
}

type AudioKind int32

const (
	AudioKind_AUDIO_KIND_UNSPECIFIED AudioKind = 0
	AudioKind_AUDIO_KIND_MIC         AudioKind = 1
	AudioKind_AUDIO_KIND_TTS         AudioKind = 2
	AudioKind_AUDIO_KIND_BEEP        AudioKind = 3
)

// Enum value maps for AudioKind.
var (
	AudioKind_name = map[int32]string{
		0: "AUDIO_KIND_UNSPECIFIED",
		1: "AUDIO_KIND_MIC",
		2: "AUDIO_KIND_TTS",
		3: "AUDIO_KIND_BEEP",
	}
	AudioKind_value = map[string]int32{
		"AUDIO_KIND_UNSPECIFIED": 0,
		"AUDIO_KIND_MIC":         1,
		"AUDIO_KIND_TTS":         2,
		"AUDIO_KIND_BEEP":        3,
	}
)

func (x AudioKind) Enum() *AudioKind {
	p := new(AudioKind)
	*p = x
	return p
}

func (x AudioKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tether_proto_enumTypes[1].Descriptor()
}

func (AudioKind) Type() protoreflect.EnumType {
	return &file_tether_proto_enumTypes[1]
}

func (x AudioKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioKind.Descriptor instead.
func (AudioKind) EnumDescriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{1}
}

type AudioCodec int32

const (
	AudioCodec_AUDIO_CODEC_UNSPECIFIED    AudioCodec = 0
	AudioCodec_AUDIO_CODEC_OPUS_8K_16KBPS AudioCodec = 1
)

// Enum value maps for AudioCodec.
var (
	AudioCodec_name = map[int32]string{
		0: "AUDIO_CODEC_UNSPECIFIED",
		1: "AUDIO_CODEC_OPUS_8K_16KBPS",
	}
	AudioCodec_value = map[string]int32{
		"AUDIO_CODEC_UNSPECIFIED":    0,
		"AUDIO_CODEC_OPUS_8K_16KBPS": 1,
	}
)

func (x AudioCodec) Enum() *AudioCodec {
	p := new(AudioCodec)
	*p = x
	return p
}

func (x AudioCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_tether_proto_enumTypes[2].Descriptor()
}

func (AudioCodec) Type() protoreflect.EnumType {
	return &file_tether_proto_enumTypes[2]
}

func (x AudioCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioCodec.Descriptor instead.
func (AudioCodec) EnumDescriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{2}
}

type ConvKind int32

const (
	ConvKind_CONV_KIND_UNSPECIFIED ConvKind = 0
	ConvKind_CONV_KIND_MATRIX      ConvKind = 1
	ConvKind_CONV_KIND_FORGE       ConvKind = 2
	ConvKind_CONV_KIND_BROADCAST   ConvKind = 3
)

// Enum value maps for ConvKind.
var (
	ConvKind_name = map[int32]string{
		0: "CONV_KIND_UNSPECIFIED",
		1: "CONV_KIND_MATRIX",
		2: "CONV_KIND_FORGE",
		3: "CONV_KIND_BROADCAST",
	}
	ConvKind_value = map[string]int32{
		"CONV_KIND_UNSPECIFIED": 0,
		"CONV_KIND_MATRIX":      1,
		"CONV_KIND_FORGE":       2,
		"CONV_KIND_BROADCAST":   3,
	}
)

func (x ConvKind) Enum() *ConvKind {
	p := new(ConvKind)
	*p = x
	return p
}

func (x ConvKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConvKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tether_proto_enumTypes[3].Descriptor()
}

func (ConvKind) Type() protoreflect.EnumType {
	return &file_tether_proto_enumTypes[3]
}

func (x ConvKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConvKind.Descriptor instead.
func (ConvKind) EnumDescriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{3}
}

// All packets on the LoRa link share this envelope.
type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"fixed32,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // = 1
	TargetId        *NodeId                `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                        // 0xFFFF = broadcast
	SenderId        *NodeId                `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConversationId  []byte                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`            // 16 bytes (UUID)
	MessageId       uint32                 `protobuf:"fixed32,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                         // monotonic per (target, conversation)
	SeqNum          uint32                 `protobuf:"fixed32,6,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`                                  // chunk index, 0-based
	TotalSeqs       uint32                 `protobuf:"fixed32,7,opt,name=total_seqs,json=totalSeqs,proto3" json:"total_seqs,omitempty"`                         // total chunks in this message
	MsgType         MsgType                `protobuf:"varint,8,opt,name=msg_type,json=msgType,proto3,enum=tether.v1.MsgType" json:"msg_type,omitempty"`         // START / DATA / END / ACK / TTS_DATA / TTS_END / UI_UPDATE
	AudioKind       AudioKind              `protobuf:"varint,9,opt,name=audio_kind,json=audioKind,proto3,enum=tether.v1.AudioKind" json:"audio_kind,omitempty"` // 0=mic, 1=tts, 2=beep
	Flags           uint32                 `protobuf:"fixed32,10,opt,name=flags,proto3" json:"flags,omitempty"`                                                 // bit0=RETRANSMIT, bit1=LAST_TTS_CHUNK
	Payload         []byte                 `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`                                               // ≤ 227 bytes
	HeaderCrc       uint32                 `protobuf:"fixed32,12,opt,name=header_crc,json=headerCrc,proto3" json:"header_crc,omitempty"`                        // CRC-16/CCITT, but stored as uint32
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tether_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tether_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetTargetId() *NodeId {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *Envelope) GetSenderId() *NodeId {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *Envelope) GetConversationId() []byte {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *Envelope) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Envelope) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Envelope) GetTotalSeqs() uint32 {
	if x != nil {
		return x.TotalSeqs
	}
	return 0
}

func (x *Envelope) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_UNSPECIFIED
}

func (x *Envelope) GetAudioKind() AudioKind {
	if x != nil {
		return x.AudioKind
	}
	return AudioKind_AUDIO_KIND_UNSPECIFIED
}

func (x *Envelope) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHeaderCrc() uint32 {
	if x != nil {
		return x.HeaderCrc
	}
	return 0
}

// START payload
type StartInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Codec            AudioCodec             `protobuf:"varint,1,opt,name=codec,proto3,enum=tether.v1.AudioCodec" json:"codec,omitempty"`
	SampleRateHz     uint32                 `protobuf:"fixed32,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`             // 8000
	BitrateBps       uint32                 `protobuf:"fixed32,3,opt,name=bitrate_bps,json=bitrateBps,proto3" json:"bitrate_bps,omitempty"`                     // 16000
	DurationMs       uint32                 `protobuf:"fixed32,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                     // total recording length
	PayloadSizeBytes uint32                 `protobuf:"fixed32,5,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"` // bytes per chunk (post-fragmentation)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartInfo) Reset() {
	*x = StartInfo{}
	mi := &file_tether_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInfo) ProtoMessage() {}

func (x *StartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tether_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInfo.ProtoReflect.Descriptor instead.
func (*StartInfo) Descriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{1}
}

func (x *StartInfo) GetCodec() AudioCodec {
	if x != nil {
		return x.Codec
	}
	return AudioCodec_AUDIO_CODEC_UNSPECIFIED
}

func (x *StartInfo) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *StartInfo) GetBitrateBps() uint32 {
	if x != nil {
		return x.BitrateBps
	}
	return 0
}

func (x *StartInfo) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StartInfo) GetPayloadSizeBytes() uint32 {
	if x != nil {
		return x.PayloadSizeBytes
	}
	return 0
}

// ACK payload
type Ack struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  []byte                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 16 bytes
	MessageId       uint32                 `protobuf:"fixed32,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NextExpectedSeq uint32                 `protobuf:"fixed32,3,opt,name=next_expected_seq,json=nextExpectedSeq,proto3" json:"next_expected_seq,omitempty"`
	AckBitmapLo     uint32                 `protobuf:"fixed32,4,opt,name=ack_bitmap_lo,json=ackBitmapLo,proto3" json:"ack_bitmap_lo,omitempty"` // 16 bits covering [next..next+15]
	AckBitmapHi     uint32                 `protobuf:"fixed32,5,opt,name=ack_bitmap_hi,json=ackBitmapHi,proto3" json:"ack_bitmap_hi,omitempty"` // 16 bits covering [next+16..next+31]
	Crc             uint32                 `protobuf:"fixed32,6,opt,name=crc,proto3" json:"crc,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_tether_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_tether_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetConversationId() []byte {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *Ack) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Ack) GetNextExpectedSeq() uint32 {
	if x != nil {
		return x.NextExpectedSeq
	}
	return 0
}

func (x *Ack) GetAckBitmapLo() uint32 {
	if x != nil {
		return x.AckBitmapLo
	}
	return 0
}

func (x *Ack) GetAckBitmapHi() uint32 {
	if x != nil {
		return x.AckBitmapHi
	}
	return 0
}

func (x *Ack) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

// UI_UPDATE payload — pushes a new conversation to the M5
type ConvInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConversationId     []byte                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // ≤ 24 chars (truncated by M5)
	Kind               ConvKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=tether.v1.ConvKind" json:"kind,omitempty"`
	Target             string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                                    // matrix room_id or forge session UUID
	EncryptionKey      []byte                 `protobuf:"bytes,5,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"` // 16 bytes; HKDF-derived
	LastActivityUnixMs uint64                 `protobuf:"fixed64,6,opt,name=last_activity_unix_ms,json=lastActivityUnixMs,proto3" json:"last_activity_unix_ms,omitempty"`
	UnreadCount        uint32                 `protobuf:"fixed32,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Remove             bool                   `protobuf:"varint,8,opt,name=remove,proto3" json:"remove,omitempty"` // true = remove this conversation
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConvInfo) Reset() {
	*x = ConvInfo{}
	mi := &file_tether_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvInfo) ProtoMessage() {}

func (x *ConvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tether_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvInfo.ProtoReflect.Descriptor instead.
func (*ConvInfo) Descriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{3}
}

func (x *ConvInfo) GetConversationId() []byte {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *ConvInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConvInfo) GetKind() ConvKind {
	if x != nil {
		return x.Kind
	}
	return ConvKind_CONV_KIND_UNSPECIFIED
}

func (x *ConvInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ConvInfo) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *ConvInfo) GetLastActivityUnixMs() uint64 {
	if x != nil {
		return x.LastActivityUnixMs
	}
	return 0
}

func (x *ConvInfo) GetUnreadCount() uint32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConvInfo) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

type NodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	mi := &file_tether_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_tether_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_tether_proto_rawDescGZIP(), []int{4}
}

func (x *NodeId) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_tether_proto protoreflect.FileDescriptor

const file_tether_proto_rawDesc = "" +
	"\n" +
	"\ftether.proto\x12\ttether.v1\"\xc8\x03\n" +
	"\bEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\aR\x0fprotocolVersion\x12.\n" +
	"\ttarget_id\x18\x02 \x01(\v2\x11.tether.v1.NodeIdR\btargetId\x12.\n" +
	"\tsender_id\x18\x03 \x01(\v2\x11.tether.v1.NodeIdR\bsenderId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\fR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\aR\tmessageId\x12\x17\n" +
	"\aseq_num\x18\x06 \x01(\aR\x06seqNum\x12\x1d\n" +
	"\n" +
	"total_seqs\x18\a \x01(\aR\ttotalSeqs\x12-\n" +
	"\bmsg_type\x18\b \x01(\x0e2\x12.tether.v1.MsgTypeR\amsgType\x123\n" +
	"\n" +
	"audio_kind\x18\t \x01(\x0e2\x14.tether.v1.AudioKindR\taudioKind\x12\x14\n" +
	"\x05flags\x18\n" +
	" \x01(\aR\x05flags\x12\x18\n" +
	"\apayload\x18\v \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"header_crc\x18\f \x01(\aR\theaderCrc\"\xce\x01\n" +
	"\tStartInfo\x12+\n" +
	"\x05codec\x18\x01 \x01(\x0e2\x15.tether.v1.AudioCodecR\x05codec\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\aR\fsampleRateHz\x12\x1f\n" +
	"\vbitrate_bps\x18\x03 \x01(\aR\n" +
	"bitrateBps\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\aR\n" +
	"durationMs\x12,\n" +
	"\x12payload_size_bytes\x18\x05 \x01(\aR\x10payloadSizeBytes\"\xd3\x01\n" +
	"\x03Ack\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\fR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\aR\tmessageId\x12*\n" +
	"\x11next_expected_seq\x18\x03 \x01(\aR\x0fnextExpectedSeq\x12\"\n" +
	"\rack_bitmap_lo\x18\x04 \x01(\aR\vackBitmapLo\x12\"\n" +
	"\rack_bitmap_hi\x18\x05 \x01(\aR\vackBitmapHi\x12\x10\n" +
	"\x03crc\x18\x06 \x01(\aR\x03crc\"\x9d\x02\n" +
	"\bConvInfo\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\fR\x0econversationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x13.tether.v1.ConvKindR\x04kind\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12%\n" +
	"\x0eencryption_key\x18\x05 \x01(\fR\rencryptionKey\x121\n" +
	"\x15last_activity_unix_ms\x18\x06 \x01(\x06R\x12lastActivityUnixMs\x12!\n" +
	"\funread_count\x18\a \x01(\aR\vunreadCount\x12\x16\n" +
	"\x06remove\x18\b \x01(\bR\x06remove\"\x1e\n" +
	"\x06NodeId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\aR\x05value*\xb3\x01\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eMSG_TYPE_START\x10\x01\x12\x11\n" +
	"\rMSG_TYPE_DATA\x10\x02\x12\x10\n" +
	"\fMSG_TYPE_END\x10\x03\x12\x10\n" +
	"\fMSG_TYPE_ACK\x10\x04\x12\x15\n" +
	"\x11MSG_TYPE_TTS_DATA\x10\x05\x12\x14\n" +
	"\x10MSG_TYPE_TTS_END\x10\x06\x12\x16\n" +
	"\x12MSG_TYPE_UI_UPDATE\x10\a*d\n" +
	"\tAudioKind\x12\x1a\n" +
	"\x16AUDIO_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUDIO_KIND_MIC\x10\x01\x12\x12\n" +
	"\x0eAUDIO_KIND_TTS\x10\x02\x12\x13\n" +
	"\x0fAUDIO_KIND_BEEP\x10\x03*I\n" +
	"\n" +
	"AudioCodec\x12\x1b\n" +
	"\x17AUDIO_CODEC_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAUDIO_CODEC_OPUS_8K_16KBPS\x10\x01*i\n" +
	"\bConvKind\x12\x19\n" +
	"\x15CONV_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CONV_KIND_MATRIX\x10\x01\x12\x13\n" +
	"\x0fCONV_KIND_FORGE\x10\x02\x12\x17\n" +
	"\x13CONV_KIND_BROADCAST\x10\x03B9Z7github.com/jbutlerdev/tether/go/pkg/protocol/protocolpbb\x06proto3"

var (
	file_tether_proto_rawDescOnce sync.Once
	file_tether_proto_rawDescData []byte
)

func file_tether_proto_rawDescGZIP() []byte {
	file_tether_proto_rawDescOnce.Do(func() {
		file_tether_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tether_proto_rawDesc), len(file_tether_proto_rawDesc)))
	})
	return file_tether_proto_rawDescData
}

var file_tether_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_tether_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tether_proto_goTypes = []any{
	(MsgType)(0),      // 0: tether.v1.MsgType
	(AudioKind)(0),    // 1: tether.v1.AudioKind
	(AudioCodec)(0),   // 2: tether.v1.AudioCodec
	(ConvKind)(0),     // 3: tether.v1.ConvKind
	(*Envelope)(nil),  // 4: tether.v1.Envelope
	(*StartInfo)(nil), // 5: tether.v1.StartInfo
	(*Ack)(nil),       // 6: tether.v1.Ack
	(*ConvInfo)(nil),  // 7: tether.v1.ConvInfo
	(*NodeId)(nil),    // 8: tether.v1.NodeId
}
var file_tether_proto_depIdxs = []int32{
	8, // 0: tether.v1.Envelope.target_id:type_name -> tether.v1.NodeId
	8, // 1: tether.v1.Envelope.sender_id:type_name -> tether.v1.NodeId
	0, // 2: tether.v1.Envelope.msg_type:type_name -> tether.v1.MsgType
	1, // 3: tether.v1.Envelope.audio_kind:type_name -> tether.v1.AudioKind
	2, // 4: tether.v1.StartInfo.codec:type_name -> tether.v1.AudioCodec
	3, // 5: tether.v1.ConvInfo.kind:type_name -> tether.v1.ConvKind
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tether_proto_init() }
func file_tether_proto_init() {
	if File_tether_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tether_proto_rawDesc), len(file_tether_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tether_proto_goTypes,
		DependencyIndexes: file_tether_proto_depIdxs,
		EnumInfos:         file_tether_proto_enumTypes,
		MessageInfos:      file_tether_proto_msgTypes,
	}.Build()
	File_tether_proto = out.File
	file_tether_proto_goTypes = nil
	file_tether_proto_depIdxs = nil
}
